name: CI - Quick tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run quick pytest (persistence test)
        env:
          PYTHONPATH: ${{ github.workspace }}
          SCALED_SIGLADO_PERSIST: '1'
        run: |
          pytest -q tests/test_scaled_persist.py::test_scaled_persist_creates_file -q -r a
